version: '3.8'

services:
  # 1. Data Base
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  # 2. API
  backend:
    #build: ./backend
    image: lizdaisy/example-back:${ENV_TAG}
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # 3. UI
  frontend:
    #build: ./frontend
    image: lizdaisy/example-front:${ENV_TAG}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:                  
      - VITE_API_URL=${FRONTEND_URL}
